---
- hosts: webservers
  become: yes
  vars_files:
    - /home/ansible/adv-ansible/labs/ansible-vault/conf/confidential
  tasks:
    - name: install httpd
      apt:
        name: apache2
        state: latest
      notify: httpd service
      tags:
        - base-install
  handlers:
    - name: Restart and enable httpd
      service:
        name: apache2
        state: restarted
        enabled: yes
      listen: httpd service